### ISSUE TITLE
Onboarding Series - Customer Experience

### ISSUE THREAD

**Issue by BDavydov** [3drepo/3D-Repo-Product-Team#10]
### Description
Establish the onboarding series for free, pilot and paying customers.

### Sub-tasks
- [ ] Create a custom attribute (questionnaire)
- [ ] Map out the onboarding routes
- New User
- Paid Pilot
- Paying Customer
- [ ] Update & add new Email templates
- [ ] Create new Product Tours

### Pictures/Resources
![image](https://user-images.githubusercontent.com/19904513/125587745-db241182-ccdf-4830-9086-49d0cd08cef4.png)
