### ISSUE TITLE
Zoho Forms to Intercom Zapier Integration

### ISSUE THREAD

**Issue by BDavydov** [3drepo/3D-Repo-Product-Team#13]
### Description
Integrate Zoho forms with Intercom using Zapier integration platform.

### Sub-tasks
- [x] Review Zoho Form Response body
- [x] Connect Zoho & Intercom to Zapier
- [x] Test Zoho to Intercom through Zapier

### Links
- https://zapier.com/app/zaps
- https://forms.zoho.eu/3drepo/home#myforms
- https://developers.intercom.com/intercom-api-reference/reference

**Comment by BDavydov** [comment]
Unfortunately, Zapier only offers a trigger for new conversations of Intercom Users only. Even when you create a new Lead and use the Lead's ID to create a conversation it comes back with an error. Intercom's APIs state that you need to declare the role associated with the contact ie. `user` or `lead`
https://developers.intercom.com/intercom-api-reference/reference#create-a-conversation
![image](https://user-images.githubusercontent.com/19904513/125963803-dbdd7173-7221-48f7-9167-4012813492f1.png)

I have contacted Zapier support to tell me what are the options for tweaking their connector and allowing us to create new conversations with Leads rather than existing Users. Waiting for their response.

**Comment by BDavydov** [comment]
We're scrapping the idea of Zapier, due to technical difficulties and cost plans. Currently, we're testing the Power Automate solution.
