### ISSUE TITLE
Configure Model Streaming project for Unreal

### ISSUE THREAD

**Issue by mosment3DRepo** [3drepo/3D-Repo-Product-Team#20]
### Description

To assist with Sebastian's work on Geometry streaming in Unreal we need to set up a set of model data in 3D Repo

### Sub-tasks
- [ ] Create model streaming teamspace and get additional space/users
- [ ] Upload 40 Leadenhall models to 3D Repo teamspace
- [ ] Group elements based on location/type
