### ISSUE TITLE
Teamspace: Login/signup screens

### ISSUE THREAD

**Issue by george-hadfield** [3drepo/3D-Repo-Product-Team#22]
### Sub-tasks
- [ ] Login screen desktop
- [ ] Login screen tablet
- [ ] Login screen mobile
- [ ] Sign up screen desktop
- [ ] Sign up screen tablet
- [ ] Sign up screen mobile
