### ISSUE TITLE
Teamspace: Users screens

### ISSUE THREAD

**Issue by george-hadfield** [3drepo/3D-Repo-Product-Team#25]
### Sub-tasks
- [ ] Desktop users page
- [ ] Tablet users page
- [ ] Mobile users page
