### ISSUE TITLE
AEC PCR - PSQ Rooms Dashboard

### ISSUE THREAD

**Issue by miadibe** [3drepo/3D-Repo-Product-Team#26]
### Description
Prepare Power BI dashboards for PSQ Rooms from the Revit model

### Sub-tasks
- [ ] Dynamo to import dummy data on room progress and status
- [ ] Create Smart groups with room status and progress
- [ ] Update Power BI dashboard to contain colour overrides in the visual viewer
- [ ] Confirm & validate csv data with Max and Alessandro
