### ISSUE TITLE
Test Civil3D plugin Model Upload

### ISSUE THREAD

**Issue by mosment3DRepo** [3drepo/3D-Repo-Product-Team#35]
### Description
Once Carmen has signed off the updated version of the Civil 3D plugin we need to test it with the client model (https://www.dropbox.com/home/3D%20Repo%20Team%20Folder/Clients/Prospects/WSP/Projects%20and%20data/WSP%20Pilot?preview=3DRepoTest_solids.dwg) that was giving us problems.

Check the comments of the issue to see some additional info so we can test if it performs as intended https://github.com/3drepo/3drepoPlugin/issues/320

### Sub-tasks
- [x] Test Model upload
- [x] Report back on the PR if there is anything wrong
- [x] Pass executable on to Jack to give to client, make sure we are clear this is pre-release and if it functions as expected we will put it on the website by the end of September
- [x] Get it done by Thursday the 26th of August

### Links
https://github.com/3drepo/3drepoPlugin/issues/320

**Comment by miadibe** [comment]
This is done. Export/Publish successful with relevant Unsupported type message after processing. Model comes through in 3D Repo. Issue is closed. 
![civil3dv418-3](https://user-images.githubusercontent.com/56918163/130484273-25a5afde-b038-49ad-8917-d2cf7c207421.JPG)
![civil3dv418-2](https://user-images.githubusercontent.com/56918163/130484277-9b92e1bd-d353-4b6f-8c13-4d155ed591cf.JPG)
![civil3dv418](https://user-images.githubusercontent.com/56918163/130484279-c598b564-f022-48d7-8721-48ad21f46419.JPG)
