### ISSUE TITLE
Navis 2D Lines QA

### ISSUE THREAD

**Issue by mosment3DRepo** [3drepo/3D-Repo-Product-Team#36]
### Description
Christos has released a new version of the Navisworks plugin with 2D lines enabled (see teams chat [here for download link](https://teams.microsoft.com/l/message/19:794c1bfdf99d4853bb2f37b1d7ff8593@thread.tacv2/1628254494164?tenantId=501779ee-77d4-42cf-8eda-fb5e4a03ab71&groupId=349e37fe-7f62-4823-b57a-b9175ef21d44&parentMessageId=1628254494164&teamName=3D%20Repo%20Ltd&channelName=Notifications&createdTime=1628254494164))

We need to test some models in Navisoworks by importing DGN or DWG (or any other method of getting 2D lines into Navisworks) and review the results

Issue list already created here https://github.com/3drepo/3drepoPlugin/issues/319

### Sub-tasks
- [x] Find/Build some Navisworks files with 2D lines (I think andrew has some)
- [x] Upload to 3D Repo
- [x] Report any issues or unexpected behaviour to github issue

**Comment by BDavydov** [comment]
@mosment3DRepo This is now done and all the feedback is on GitHub.
