### ISSUE TITLE
HOK Revit models for UE

### ISSUE THREAD

**Issue by BDavydov** [3drepo/3D-Repo-Product-Team#38]
### Sub-tasks
- [x] Record models in Revit
- [x] Upload models to 3D Repo
- [x] Record models in 3D Repo 
- [x] Record models in UE
