### ISSUE TITLE
PowerBI Template HTML

### ISSUE THREAD

**Issue by mosment3DRepo** [3drepo/3D-Repo-Product-Team#4]
### Description
In order to streamline the creation of Dashboards for the AEC Production Control Room project we need to create a standard method of producing dashboard layouts

### Sub-tasks
- [ ] Create HTML Content
- [ ] Build Variable dashboard query
- [ ] Set Colour Palette

### Pictures/Resources
![image](https://user-images.githubusercontent.com/62879582/125493058-46312b46-867e-4a96-9674-615900aea0dc.png)

### Links
https://www.dropbox.com/home/3D%20Repo%20Team%20Folder/Integrations/AECPCR/Dashboard%20Content

**Comment by mosment3DRepo** [comment]
@mosment3DRepo test comment

**Comment by miadibe** [comment]
@mosment3DRepo test comment

**Comment by mosment3DRepo** [comment]
@miadibe test comment

**Comment by mosment3DRepo** [comment]
passed design to @george-hadfield to take a look
