### ISSUE TITLE
AEC PCR Dashboards

### ISSUE THREAD

**Issue by miadibe** [3drepo/3D-Repo-Product-Team#40]
### Description
Use dashboard creation tool to update existing and create dashboards for PSQ

### Sub-tasks
- [ ] Get data and model to be filtered by levels
- [ ] Apply dashboard templates using CSS/HTML schemas
- [ ] Deadline Mace CTO & CIO meeting @ PSQ site September 14th with Andrew

**Comment by miadibe** [comment]
Here is how we have to deal with models that are coming in from **Navisworks into PowerBI** due to some differences in the tree structure. Typically we do _Unity_id > idmap > metadata_, with the idmap table giving us the relationship between the 2 ids.

In the case of Navisworks files we have to get the metadata id of the parent, which means an additional query to get the tree. Unfortunately the tree is an 'n' level hierarchy, so PowerBI doesn't handle it well. Here's a text based parsing process which is far from ideal but seems to work at the moment.

So the steps we need to take to get from the existing dashboard to the working one are:

- Create a table called fullTree using the Query below (paste into Advanced Editor in PowerBI)
- Delete the relationship between "idmap" & "Metadata"
- Create 2 new relationships:
       1. idmap.parent > fulltree.parent (one to one, both directions)
       2. fulltree.meta._id > Metadataa._id (one to one, both directions)
- fullTree query code:
```
let
    Source = Json.Document(Web.Contents("https://www.3drepo.io", [RelativePath="/api/"&Teamspace&"/"&#"Model ID"&"/revision/master/head/fulltree.json", Query=[key=API]])),
    subTrees = Source[subTrees],
    #"Converted to Table" = Table.FromList(subTrees, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
    #"Expanded Column1" = Table.ExpandRecordColumn(#"Converted to Table", "Column1", {"_id", "rid", "teamspace", "model", "url"}, {"Column1._id", "Column1.rid", "Column1.teamspace", "Column1.model", "Column1.url"}),
    #"Added Custom" = Table.AddColumn(#"Expanded Column1", "Custom", each Table.FromColumns({Lines.FromBinary(Web.Contents("https://www.3drepo.io", [RelativePath="/api/"&Teamspace&"/"&[Column1.model]&"/revision/master/head/fulltree.json", Query=[key=API]]), null, null, 1252)})),
    #"Removed Other Columns" = Table.SelectColumns(#"Added Custom",{"Custom"}),
    #"Expanded Custom" = Table.ExpandTableColumn(#"Removed Other Columns", "Custom", {"Column1"}, {"Column1"}),
    #"Split Column by Delimiter" = Table.ExpandListColumn(Table.TransformColumns(#"Expanded Custom", {{"Column1", Splitter.SplitTextByDelimiter("""shared_id"":""", QuoteStyle.None), let itemType = (type nullable text) meta [Serialized.Text = true] in type {itemType}}}), "Column1"),
    #"Split Column by Delimiter1" = Table.SplitColumn(#"Split Column by Delimiter", "Column1", Splitter.SplitTextByDelimiter("meta"":[""", QuoteStyle.None), {"Column1.1", "Column1.2"}),
    #"Extracted First Characters" = Table.TransformColumns(#"Split Column by Delimiter1", {{"Column1.1", each Text.Start(_, 36), type text}}),
    #"Extracted First Characters1" = Table.TransformColumns(#"Extracted First Characters", {{"Column1.2", each Text.Start(_, 36), type text}}),
    #"Filtered Rows" = Table.SelectRows(#"Extracted First Characters1", each [Column1.2] <> null and [Column1.2] <> ""),
    #"Renamed Columns" = Table.RenameColumns(#"Filtered Rows",{{"Column1.1", "shared_id"}, {"Column1.2", "meta"}})
in
    #"Renamed Columns"
```
**Relationship diagram**
![relationship diagram](https://user-images.githubusercontent.com/56918163/133042024-c95e7e46-41d1-4fda-9ae0-111cc97709e2.png)
