### ISSUE TITLE
Create Roadmap flowchart

### ISSUE THREAD

**Issue by mosment3DRepo** [3drepo/3D-Repo-Product-Team#50]
Roadmap is currently a list of tasks, but the flow of work means that a flow chart makes more sense.

- [ ] Set up mermaid Markdown page
- [ ] List out roadmap items
- [ ] Check with team
