### ISSUE TITLE
Update Teamspace designs with new headers

### ISSUE THREAD

**Issue by george-hadfield** [3drepo/3D-Repo-Product-Team#57]
### Description
Following on from design tweaks with Jozef, designs for Teamspace need to be updated, reviewed and added to Milestones for the dev team.

### Sub-tasks
- [ ] Update Containers pages
- [ ] Update Federations pages
- [ ] Update Kanban page
- [ ] Get designs approved
- [ ] Hand over to dev team and AppTension
