### ISSUE TITLE
Clinic Handover Pack

### ISSUE THREAD

**Issue by miadibe** [3drepo/3D-Repo-Product-Team#7]
### Description
Prepare Clinic model for future demos with all use cases

### Sub-tasks
- [ ] PowerBI dashboard templates
- [ ] 3DRepo.io features
- [ ] Metadata Diff
- [ ] Clean and prepare Revit files with all views
