### ISSUE TITLE
Smart Groups batch uploading workflows

### ISSUE THREAD

**Issue by BDavydov** [3drepo/3D-Repo-Product-Team#8]
### Description
Define and establish the scope of work for batch uploading smart groups. Identify areas of improvement and feature integrations.

### Sub-tasks
- [ ] Identify all options to batch upload Smart Groups
- [ ] Create a CSV Template
- [ ] Review current API setup
- [ ] Identify future feature integrations

**Comment by mosment3DRepo** [comment]
Relevant feature requesst

https://github.com/3drepo/3drepo.io/issues/2711

**Comment by BDavydov** [comment]
@mosment3DRepo There isn't really an ideal or easy way for translating Excel files into JSON. There are some converters online that consume .xls or .csv files, but the problem lies in the the arrays. For example, Rules can contain multiple lists as shown below. If there is no logic in place, it will convert rules into a new JSON list that contains no Group Name, Description & etc.
![image](https://user-images.githubusercontent.com/19904513/127283969-bdc2ce9d-b469-4bc0-b8ef-09168becb991.png)

![image](https://user-images.githubusercontent.com/19904513/127284129-c918af6c-9211-474d-9e0e-f816ac96bc69.png)

**Comment by BDavydov** [comment]
@mosment3DRepo there is an online JSON converter that actually works nicely with the nested JSON data. As a result, I'm able to generate a single group with multiple rules. Here is an example:
https://data.page/csv/json
[Tower Block Structure_groups.zip](https://github.com/3drepo/3D-Repo-Product-Team/files/6891237/Tower.Block.Structure_groups.zip)
