### ISSUE TITLE
Revit Workshared Files and Data

### ISSUE THREAD

**Issue by miadibe** [3drepo/3D-Repo-Product-Team#9]
### Description
Explore new use case for tracking model completion (owner, borrower, changes made) by revision in a dashboard for any Revit worksharing file that is synchronised with a central model.

### Sub-tasks
- [ ] Upload various RVT models to 3drepo.io (via direct upload and plugin) 
- [ ] Compare metadata shown in BIM card
- [ ] Explore Methods in ODA
- [ ] Explore Methods in Revit API
- [ ] Model Changes Diff in a PowerBI dashboard

### Links
https://coda.io/d/3D-Repo-Product-Management_dPKjhWeEmM9/Revit-Workshared-files_suIIw#_luzIQ

### Mentions
@BDavydov @mosment3DRepo
